from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models


class User(AbstractUser):
    """Модель пользователя."""

    email = models.EmailField(
        'Адрес электронной почты',
        )
    username = models.CharField(
        'Юзернейм',
        max_length=150,
        unique=True,
    )
    first_name = models.CharField(
        'Имя',
        max_length=150,
    )
    last_name = models.CharField(
        'Фамилия',
        max_length=150,
    )

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ('pk',)

    def __str__(self):
        return self.username


class Subscription(models.Model):
    user = models.ForeignKey(
        User,
        related_name='subscriber',
        verbose_name='Подписчик',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='subscriptions',
        verbose_name='Автор',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        ordering = ('-pk',)
        constraints = [
            models.UniqueConstraint(
                name='no_double_subscribe',
                fields=('user', 'author'),
            ),
            models.CheckConstraint(
                name='no_self_subscribe',
                check=~models.Q(user=models.F('author')),
            ),
        ]

    def clean(self):
        if self.author == self.user:
            raise ValidationError('Нельзя подписаться на себя.')

    def __str__(self):
        return f'{self.user.username} подписан на {self.author.username}'
